# Generated by Django 6.0.6 on 2026-06-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='service_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
