# Generated by Django 6.0.6 on 2026-06-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_subscription_created_at_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_recurring',
            field=models.BooleanField(default=True),
        ),
    ]
